[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "maskmatch"
version = "0.1.0"
description = "A package for mask matching algorithms"
authors = [
  { name = "Aaron Pumm" }
]
requires-python = ">=3.9"